name: Bug 反馈 / Bug report
description: 提交一个问题报告 / Create a bug report
labels:
  - "bug"
body:
  - type: markdown
    attributes:
      value: |
        感谢您愿意为 Ehviewer-NekoInverter 做出贡献！
        提交问题报告前，还请首先完成文末的自查步骤

        Thanks for your contribution on Ehviewer-NekoInverter Project!
        Please finish verify steps which list in the end first before create bug report

  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤 / Step to reproduce
      description: |
        在此处写下复现的方式，请详细描述每一个步骤，包括画廊链接、相关设置等
        Describe how to reproduce here, please describe each step in detail, include gallery link or settings
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id : expected
    attributes:
      label: 预期行为 / Expected behaviour
      description: |
        在此处说明正常情况下应用的预期行为
        Describe what should happened here
      placeholder: |
        它应该 ...
        It should be ...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 实际行为 / Actual Behaviour
      description: |
        在此处描绘应用的实际行为，最好附上截图或录屏
        Describe what actually happened here, screenshots or screen recordings is better
      placeholder: |
        实际上它 ...
        Actually it ...
        [截图或录屏] / [Screenshots or screen recordings]
    validations:
      required: true

  - type: textarea
    id: more
    attributes:
      label: 备注 / Addition details
      description: |
        在此处写下其他您想说的内容
        Describe addition details here
      placeholder: |
        其他有用的信息与附件
        Additional details and attachments
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: EhViewer 版本号 / EhViewer version code
      description: |
        您可以在设置 - 关于处找到版本号
        You can get version code in Settings - About
      placeholder: 1.8.0
    validations:
      required: true

  - type: input
    id: ci
    attributes:
      label: EhViewer CI 版本 / EhViewer CI Version
      description: |
        请确保您已经使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml?query=branch%3Aeh-1.8.x.x-dev) 测试，请填入您使用的 CI 版本网址
        Please make sure you have tested with the [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml?query=branch%3Aeh-1.8.x.x-dev), simply drop GitHub Action CI download page url here
      placeholder: https://github.com/EhViewer-NekoInverter/EhViewer/actions/runs/XXXXXXXXXX
    validations:
      required: true

  - type: input
    id: system
    attributes:
      label: Android 系统版本 / Android version
      description: Android 分支名称 + 版本号 / AOSP fork name + version code
      placeholder: MIUI 12.5, ArrowOS 12.1
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: 设备型号 / Device model
      description: 在此填入设备型号 / Put device model here
      placeholder: OnePlus 7 Pro, Xiaomi 12 Ultra
    validations:
      required: true

  - type: input
    id: SoC
    attributes:
      label: SoC 型号 / Soc model
      description: 在此填入 SoC 型号 / Put Soc model here
      placeholder: 骁龙 8+ Gen 1, Snapdragon 8+ Gen 1
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: 应用日志 / App logs
      description: |
        您可以通过设置-高级-导出日志 来获得日志文件，过长的日志请以文件形式上传
        You can get logs file in Settings - Advanced - Dump logcat
      placeholder: 06-15 17:44:53.704 23382 23382 E ...
    validations:
      required: true

  - type: checkboxes
    id: check
    attributes:
      label: 自查步骤 / Verify steps
      description: |
        请确保您已经遵守以下所有必选项，否则 issue 会被立即关闭
        Please ensure you have obtained all needed options, otherwise the issue will be closed immediately
      options:
      - label: 如果您有足够的时间和能力，并愿意为修复此问题提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
        required: false

      - label: 您已仔细查看并知情 [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) 中的内容 / You have checked [Q&A](https://github.com/EhViewer-NekoInverter/EhViewer/issues/18) carefully
        required: true

      - label: 您已搜索过 [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/EhViewer-NekoInverter/EhViewer/issues), No duplicate or related open issue has been found
        required: true

      - label: 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
        required: true

      - label: 您确保已使用 [最新 CI 版本](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml?query=branch%3Aeh-1.8.x.x-dev) 测试，并且该问题在最新 CI 版本中并未解决 / This bug have not solved in [latest CI version](https://github.com/EhViewer-NekoInverter/EhViewer/actions/workflows/ci.yml?query=branch%3Aeh-1.8.x.x-dev)
        required: true
